### ISSUE TITLE
new irksome user - explicit RK

### ISSUE THREAD

**Issue by rhaynes74** [firedrakeproject/Irksome#100]
Hi folks, 

A new irksome user here, ultimately will use irksome and firedrake for an adaptive, parallel wildfire simulator.

For consistency of implementation and testing, I am wondering if it is worth  "convincing" irksome to handle explicit RK methods (with the ability to handle fairly general boundary conditions) ?  And if so, is there a preferred way to do this? I have had a quick look at how PEPRK is implemented, is that a template to follow to add other explicit RK methods? Is there a list of modifications needed to the irksome src files that I should be aware of to make this work? 

Thanks,
R Haynes

**Comment by ScottMacLachlan** [comment]
You can add any Butcher Tableaux you'd like by following the patterns in `irksome/ButcherTableaux.py` and `irksome/pep_explicit_rk.py`.  To make these accessible, you need to also modify `irksome/__init__.py` to add them to what is imported along with Irksome.

The last few examples in `irksome/ButcherTableaux.py` give a concrete pattern if you want to add a specific method by just specifying its tableaux.  The WSODirk and PEP examples are better if you want to add a class of methods.

**Comment by ScottMacLachlan** [comment]
PRs that add new methods (explicit or otherwise) are always welcome!

**Comment by rckirby** [comment]
A few other comments:
1) Irksome supports explicit methods -- passing `stage_type="explicit"`
into `TimeStepper` is supported.  It's derived from DIRK stepper so just
computes one stage at a time, but it goes behind your back and tells PETSc
to never rebuild the Jacobian or preconditioner used for the mass matrix
(since it's the same even if you change the time step or have a nonlinear
problem).  I just looked to confirm this is the case, and apparently I have
a small bug that hasn't been triggered (if you do not pass in
`solver_parameters`, setting up the solver parameters in the constructor
should fail).  I'll open a PR
2) I personally have an explicit bias in favor of implicit methods.  Many
people think they need explicit methods when what they really need is a
good preconditioner.  But, at the same time, Irksome does mechanism, not
policy.  If your probably really needs explicit methods or you really don't
have a good preconditioner handy, explicit should just work.  As Scott
said, PRs adding new tableaux, whether in a 1-off way (like backward Euler
or Alexander where you just splat out some numpy arrays), a programmatic
way like the collocation families (like RadauIIA) or a
factory-of-tabulated-methods way (PEPRK, WSODIRK), are welcome.

**Comment by rhaynes74** [comment]
Hi folks, thanks for the responses, so to clarify something like

`stepper = TimeStepper(F, butcher_tableau, t, dt, u, bcs=bc, solver_parameters=luparams, stage_type="explicit")`

should do the trick after edits to ButcherTableau and __init__  and then `make install` ?   No need to specify bc_type?

**Comment by ScottMacLachlan** [comment]
`bc_type` is not a valid kwarg for `stage_type="explicit"`, so you cannot specify that in this setting

**Comment by ScottMacLachlan** [comment]
So, yes - add the Butcher Table somewhere (either in Irksome, where you should submit a PR) or locally.  If in Irksome, then edit `__init__.py` to include it in what's imported with the module, and `make install` if you're not installed in editable mode.  Then your call should work perfectly

**Comment by rhaynes74** [comment]
Just a note to say that the problem accomplishing the above is due to the issue identified in [this issue](https://github.com/firedrakeproject/Irksome/issues/102)

**Comment by ScottMacLachlan** [comment]
This should be resolved by #103.

**Comment by rckirby** [comment]
I merged #103 this morning, so strong BC with the explicit time stepper should work.  Feel free to reopen/open another issue if something breaks or you get stuck trying to add a `ButcherTableau` of your choice.
