### ISSUE TITLE
Boundary Conditions on Mixed Spaces

### ISSUE THREAD

**Issue by medinaeder** [firedrakeproject/Irksome#35]
Another bug was discovered when working with MixedSpaces. 
`UFL:ERROR Can't add expressions with different shapes.`

This is triggered when the solution is in a mixed vector space `W=V*V` where `V` is a vector space and one uses `DirichletBC(W.sub(0).sub(0) ...`
One can only specify the entire vector and not the subcomponents of some subspace.

[mfe_bcs.txt](https://github.com/firedrakeproject/Irksome/files/8412227/mfe_bcs.txt)

**Comment by rckirby** [comment]
Ok, this issue seems to appear down in `getForm`, so is probably a case we didn't expect and so aren't handling correctly.  I will try to dig in.

Usually, in elasticity one puts displacement BC on all of `u` and not just a single component.   Is this critical for your application?  If so, Nitsche-type BC could be a workaround until we get this fixed since they don't go through the `DirichletBC` path for substitutions in `getForm`.

**Comment by medinaeder** [comment]
This is not critical. 
Fortunately for my case, I can specify all of `u` and no workaround is needed. 
I disagree that in elasticity one needs to specify all of `u`, oftentimes one needs "roller" boundary conditions where only one component is specified on that boundary.

**Comment by rckirby** [comment]
Fixed in PR #36
